apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-spot-cluster-1
  region: us-east-1

managedNodeGroups:
  - name: spot-1
    instanceType: m5.large
    spot: true
    availabilityZones:
      - us-east-1a
    desiredCapacity: 3
    ssh:
      publicKeyName: kubernetes # Ensure this key pair exists in AWS
    amiFamily: AmazonLinux2 # Explicitly defining the AMI family
